### ISSUE TITLE
Panic in zerologger

### ISSUE THREAD

**Issue by moneyease** [rs/zerolog#357]
I am not sure if this is problem with zerolog (v.1.20) or way I use zerolog, here is what happens when burst of traffic hits my service.
```
fatal error: concurrent map iteration and map write

goroutine 341 [running]:
runtime.throw(0xe7c739, 0x26)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc00008f7d0 sp=0xc00008f7a0 pc=0x4381b2
runtime.mapiternext(0xc00a337380)
	/usr/local/go/src/runtime/map.go:858 +0x54c fp=0xc00008f850 sp=0xc00008f7d0 pc=0x410d2c
reflect.mapiternext(0xc00a337380)
	/usr/local/go/src/runtime/map.go:1346 +0x2b fp=0xc00008f868 sp=0xc00008f850 pc=0x46b82b
reflect.(*MapIter).Next(0xc0002d81c0, 0xd0fb40)
	/usr/local/go/src/reflect/value.go:1277 +0xd6 fp=0xc00008f890 sp=0xc00008f868 pc=0x4cab56
internal/fmtsort.Sort(0xd28740, 0xc001541170, 0x15, 0x1f4)
	/usr/local/go/src/internal/fmtsort/sort.go:63 +0x1af fp=0xc00008f940 sp=0xc00008f890 pc=0x4e09cf
fmt.(*pp).printValue(0xc0001225b0, 0xd28740, 0xc001541170, 0x15, 0x7f5300000076, 0x0)
	/usr/local/go/src/fmt/print.go:769 +0xca5 fp=0xc00008fb00 sp=0xc00008f940 pc=0x4fe905
fmt.(*pp).printArg(0xc0001225b0, 0xd28740, 0xc001541170, 0x76)
	/usr/local/go/src/fmt/print.go:712 +0x2d3 fp=0xc00008fb98 sp=0xc00008fb00 pc=0x4fd533
fmt.(*pp).doPrintf(0xc0001225b0, 0xe71f8d, 0x1b, 0xc00008fe00, 0x2, 0x2)
	/usr/local/go/src/fmt/print.go:1026 +0x168 fp=0xc00008fc88 sp=0xc00008fb98 pc=0x500b68
fmt.Sprintf(0xe71f8d, 0x1b, 0xc00008fe00, 0x2, 0x2, 0xc00a3372c0, 0xc0004c4000)
	/usr/local/go/src/fmt/print.go:219 +0x66 fp=0xc00008fce0 sp=0xc00008fc88 pc=0x4f9ea6
github.com/rs/zerolog.(*Event).Msgf(0xc00a3372c0, 0xe71f8d, 0x1b, 0xc00008fe00, 0x2, 0x2)
	/go/pkg/mod/github.com/rs/zerolog@v1.20.0/event.go:127 +0x65 fp=0xc00008fd28 sp=0xc00008fce0 pc=0x78c085

```

**Comment by rs** [comment]
You are probably passing a map that is used concurrently with no protection. This is not a zerolog issue.
